"""
send_brevo.py
--------------
Takes the HTML generated by generate_brief.py and sends it to your
Brevo contact list via Brevo's Campaign API.

Required GitHub Secrets:
  BREVO_API_KEY
  BREVO_LIST_ID
  BREVO_SENDER_EMAIL
  BREVO_SENDER_NAME

Optional:
  MAILING_ADDRESS

Usage:
  python3 polly_brief/send_brevo.py --html-file polly_brief.html

  # A second, distinct send on the same day (e.g. a monthly special
  # edition) needs its own --campaign-name -- see note below.
  python3 polly_brief/send_brevo.py --html-file polly_pulse.html \\
      --campaign-name "Polly Pulse - 2026-09" \\
      --subject "The Polly Pulse: DC hiring in September"

The script:
  1. Reads the generated HTML.
  2. Checks Brevo for an existing campaign for today's date.
  3. Refuses to create a duplicate if today's campaign was already sent
     or is currently being processed.
  4. Creates a Brevo email campaign.
  5. Sends the campaign immediately.

Campaign naming and --campaign-name
------------------------------------
build_campaign_name() defaults to "Polly Brief - {date}", and the
duplicate-prevention check in find_existing_campaign() keys off that
exact name -- it's what stops a re-run from double-sending the same
day's brief.

That's correct for the daily brief, but it becomes a problem the moment
a SECOND, different kind of send needs to go out on the same calendar
day -- e.g. a monthly "Polly Pulse" special edition running on the 1st,
same day as that day's regular daily brief. Without an override, both
sends would generate the identical campaign name ("Polly Brief -
2026-09-01"), and whichever one ran second would see the first one
already marked "sent" and silently skip itself -- not because it was
actually a duplicate, but because the duplicate check has no way to
tell two different kinds of sends apart.

--campaign-name fixes this without touching the daily brief's existing
behavior at all: when supplied, it overrides build_campaign_name()
entirely; when omitted, everything works exactly as it did before this
change. The daily workflow doesn't need to pass it. Anything with its
own send cadence (e.g. a monthly script) should pass something that
can't collide with "Polly Brief - {date}", such as "Polly Pulse -
{year}-{month}".
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import sys

import requests


BREVO_API_BASE = "https://api.brevo.com/v3"

# These statuses mean the campaign has already gone out or is actively
# being sent. We do not create another campaign in these cases.
ALREADY_SENT_STATUSES = {
    "sent",
    "queued",
    "in_process",
}


def _headers(api_key: str) -> dict:
    """Return standard Brevo API headers."""
    return {
        "accept": "application/json",
        "content-type": "application/json",
        "api-key": api_key,
    }


def require_env(name: str) -> str:
    """Get a required environment variable or stop with a clear error."""
    value = os.getenv(name)

    if not value:
        raise RuntimeError(
            f"Required environment variable is missing: {name}"
        )

    return value


def find_existing_campaign(
    api_key: str,
    campaign_name: str,
) -> dict | None:
    """
    Look for an existing campaign with the supplied internal name.

    Only campaigns in an already-sent or currently-processing state
    prevent creation of a new campaign.
    """

    response = requests.get(
        f"{BREVO_API_BASE}/emailCampaigns",
        headers=_headers(api_key),
        params={
            "limit": 50,
            "offset": 0,
            "sort": "desc",
        },
        timeout=30,
    )

    response.raise_for_status()

    campaigns = response.json().get("campaigns", [])

    for campaign in campaigns:
        if (
            campaign.get("name") == campaign_name
            and campaign.get("status") in ALREADY_SENT_STATUSES
        ):
            return campaign

    return None


def create_campaign(
    api_key: str,
    campaign_name: str,
    subject: str,
    html_content: str,
    sender_email: str,
    sender_name: str,
    list_id: int,
) -> int:
    """Create a Brevo email campaign and return its campaign ID."""

    payload = {
        "name": campaign_name,
        "subject": subject,
        "sender": {
            "name": sender_name,
            "email": sender_email,
        },
        "htmlContent": html_content,
        "recipients": {
            "listIds": [list_id],
        },
    }

    response = requests.post(
        f"{BREVO_API_BASE}/emailCampaigns",
        headers=_headers(api_key),
        json=payload,
        timeout=30,
    )

    if not response.ok:
        raise RuntimeError(
            "Brevo campaign creation failed.\n"
            f"HTTP {response.status_code}\n"
            f"Response: {response.text}"
        )

    data = response.json()

    campaign_id = data.get("id")

    if not campaign_id:
        raise RuntimeError(
            "Brevo did not return a campaign ID.\n"
            f"Response: {response.text}"
        )

    return int(campaign_id)


def send_campaign(
    api_key: str,
    campaign_id: int,
) -> None:
    """Tell Brevo to send the campaign immediately."""

    response = requests.post(
        f"{BREVO_API_BASE}/emailCampaigns/{campaign_id}/sendNow",
        headers=_headers(api_key),
        timeout=30,
    )

    if not response.ok:
        raise RuntimeError(
            "Brevo sendNow failed.\n"
            f"HTTP {response.status_code}\n"
            f"Response: {response.text}"
        )


def read_html_file(path: str) -> str:
    """Read the generated HTML file."""

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"HTML file was not found: {path}"
        )

    with open(path, "r", encoding="utf-8") as file:
        html = file.read()

    if not html.strip():
        raise RuntimeError(
            f"HTML file is empty: {path}"
        )

    return html


def add_mailing_address(
    html_content: str,
    mailing_address: str | None,
) -> str:
    """
    Add the physical mailing address required for commercial email
    if one was supplied and it is not already present.

    The address is inserted immediately before </body>.
    """

    if not mailing_address:
        return html_content

    # Avoid adding the address twice if generate_brief.py already
    # included it.
    if mailing_address.lower() in html_content.lower():
        return html_content

    footer = f"""
<div style="
    margin-top: 40px;
    padding-top: 20px;
    border-top: 1px solid #dddddd;
    color: #777777;
    font-family: Arial, sans-serif;
    font-size: 12px;
    line-height: 1.5;
    text-align: center;
">
    <p>{mailing_address}</p>
</div>
"""

    if "</body>" in html_content.lower():
        lower_html = html_content.lower()
        body_position = lower_html.rfind("</body>")

        return (
            html_content[:body_position]
            + footer
            + html_content[body_position:]
        )

    return html_content + footer


def build_campaign_name(today: dt.date) -> str:
    """Create the internal campaign name used for idempotency.

    This is the DEFAULT used when --campaign-name isn't supplied on the
    command line -- see the module docstring above for why a second,
    distinct send on the same day needs to override this rather than
    share it."""

    return f"Polly Brief - {today.isoformat()}"


def build_subject(today: dt.date) -> str:
    """
    Default public email subject.

    The actual newsletter headline remains inside the generated HTML.
    """

    return f"The Polly Brief — {today.strftime('%B %-d, %Y')}"


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(
        description="Send The Polly Brief through Brevo."
    )

    parser.add_argument(
        "--html-file",
        required=True,
        help="Path to the generated Polly Brief HTML file.",
    )

    parser.add_argument(
        "--address",
        default=None,
        help="Physical mailing address to include in the email footer.",
    )

    parser.add_argument(
        "--subject",
        default=None,
        help="Optional custom email subject.",
    )

    parser.add_argument(
        "--campaign-name",
        default=None,
        help=(
            "Optional override for the internal Brevo campaign name "
            "used for duplicate-prevention. Defaults to "
            "'Polly Brief - {date}' when omitted, which is correct for "
            "the daily brief. Anything sending a SECOND, different "
            "email on the same calendar day (e.g. a monthly special "
            "edition) must pass a distinct name here, or it will "
            "collide with the daily brief's campaign name and be "
            "silently skipped as a false duplicate -- see the module "
            "docstring for the full explanation."
        ),
    )

    return parser.parse_args()


def main() -> int:
    """Main application entry point."""

    args = parse_args()

    print("========================================")
    print("        THE POLLY BRIEF → BREVO")
    print("========================================")

    # ---------------------------------------------------------
    # 1. Read environment variables
    # ---------------------------------------------------------

    print("Loading Brevo configuration...")

    api_key = require_env("BREVO_API_KEY")
    list_id_raw = require_env("BREVO_LIST_ID")
    sender_email = require_env("BREVO_SENDER_EMAIL")
    sender_name = require_env("BREVO_SENDER_NAME")

    try:
        list_id = int(list_id_raw)
    except ValueError:
        raise RuntimeError(
            f"BREVO_LIST_ID must be numeric. Received: {list_id_raw}"
        )

    mailing_address = (
        args.address
        or os.getenv("MAILING_ADDRESS")
        or ""
    )

    print(f"Sender: {sender_name} <{sender_email}>")
    print(f"Brevo list ID: {list_id}")

    # ---------------------------------------------------------
    # 2. Read generated HTML
    # ---------------------------------------------------------

    print(f"Reading HTML: {args.html_file}")

    html_content = read_html_file(args.html_file)

    print(
        f"HTML loaded successfully "
        f"({len(html_content):,} characters)."
    )

    # ---------------------------------------------------------
    # 3. Add mailing address if configured
    # ---------------------------------------------------------

    if mailing_address:
        html_content = add_mailing_address(
            html_content,
            mailing_address,
        )
        print("Mailing address included.")
    else:
        print(
            "WARNING: MAILING_ADDRESS is not configured. "
            "Make sure the generated HTML already contains "
            "your physical mailing address."
        )

    # ---------------------------------------------------------
    # 4. Establish today's campaign name
    # ---------------------------------------------------------

    today = dt.date.today()

    # --campaign-name overrides the default when supplied (e.g. a
    # monthly special edition passing its own distinct name). Omitted
    # entirely, this is identical to the original behavior.
    campaign_name = (
        args.campaign_name
        or build_campaign_name(today)
    )

    subject = (
        args.subject
        or build_subject(today)
    )

    print(f"Campaign name: {campaign_name}")
    print(f"Subject: {subject}")

    # ---------------------------------------------------------
    # 5. Idempotency check
    # ---------------------------------------------------------

    print("Checking Brevo for an existing campaign...")

    existing_campaign = find_existing_campaign(
        api_key,
        campaign_name,
    )

    if existing_campaign:
        campaign_id = existing_campaign.get("id")
        status = existing_campaign.get("status")

        print("")
        print("========================================")
        print(" DUPLICATE SEND PREVENTED")
        print("========================================")
        print(
            f"Campaign already exists: {campaign_name}"
        )
        print(f"Campaign ID: {campaign_id}")
        print(f"Status: {status}")
        print("")
        print(
            "No new campaign was created and no email was sent."
        )

        return 0

    print("No previously sent campaign found for today.")

    # ---------------------------------------------------------
    # 6. Create campaign
    # ---------------------------------------------------------

    print("Creating Brevo campaign...")

    campaign_id = create_campaign(
        api_key=api_key,
        campaign_name=campaign_name,
        subject=subject,
        html_content=html_content,
        sender_email=sender_email,
        sender_name=sender_name,
        list_id=list_id,
    )

    print(f"Campaign created successfully. ID: {campaign_id}")

    # ---------------------------------------------------------
    # 7. Send campaign
    # ---------------------------------------------------------

    print("Sending campaign through Brevo...")

    send_campaign(
        api_key=api_key,
        campaign_id=campaign_id,
    )

    # ---------------------------------------------------------
    # 8. Success
    # ---------------------------------------------------------

    print("")
    print("========================================")
    print("          BREVO SEND SUCCESS")
    print("========================================")
    print(f"Campaign: {campaign_name}")
    print(f"Campaign ID: {campaign_id}")
    print(f"Subject: {subject}")
    print("")
    print("The Polly Brief has been sent through Brevo.")
    print("========================================")

    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())

    except requests.exceptions.RequestException as exc:
        print("")
        print("========================================")
        print("          BREVO API ERROR")
        print("========================================")
        print(str(exc))
        print("========================================")
        sys.exit(1)

    except Exception as exc:
        print("")
        print("========================================")
        print("             SEND ERROR")
        print("========================================")
        print(str(exc))
        print("========================================")
        sys.exit(1)
