"""
send_brevo.py
--------------
Takes the HTML already generated by generate_brief.py and sends it to your
Brevo contact list via Brevo's Campaign API (not the raw transactional API).

Why the Campaign API specifically, not just "send an email": Brevo
auto-attaches a working, one-click unsubscribe link to every campaign send
and permanently honors opt-outs -- that's a legal requirement for bulk/
promotional email (CAN-SPAM, GDPR, etc.), and this way we get it for free
without building or hosting anything ourselves.

Required environment variables (set these as GitHub Secrets):
  BREVO_API_KEY     - from Brevo dashboard > SMTP & API > API Keys
  BREVO_LIST_ID     - the numeric ID of your subscriber list in Brevo
  BREVO_SENDER_EMAIL - a verified sender address on your domain (e.g. brief@thepolly.co)
  BREVO_SENDER_NAME  - display name, e.g. "The Polly Brief"

CAN-SPAM requires a physical mailing address in the email body -- Brevo does
NOT add this for you. Set MAILING_ADDRESS below or pass --address.

Idempotency: every campaign is created with an internal name of the form
"Polly Brief - YYYY-MM-DD" (separate from the public subject line, which
varies with the day's headline). Before creating a new campaign, we check
Brevo for an existing campaign with that name that has already been sent
or is in the middle of sending, and refuse to create a duplicate if found.
This protects against double-sends caused by a retried/re-triggered
workflow run.
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import sys

import requests

BREVO_API_BASE = "https://api.brevo.com/v3"

# Statuses that mean "this campaign has already gone out, or is actively
# going out" -- anything in this set blocks a new send for the same day.
ALREADY_SENT_STATUSES = {"sent", "queued", "in_process"}


def _headers(api_key: str) -> dict:
    return {
        "accept": "application/json",
        "content-type": "application/json",
        "api-key": api_key,
    }


def find_existing_campaign(api_key: str, campaign_name: str) -> dict | None:
    """Look for a campaign already created today with this internal name.

    Returns the campaign dict if one exists in an already-sent/in-progress
    state, otherwise None. Only checks the most recent 50 campaigns since
    that's more than enough to cover "did today's brief already go out."
    """
    resp = requests.get(
        f"{BREVO_API_BASE}/emailCampaigns",
        headers=_headers(api_key),
        params={"limit": 50, "offset": 0, "sort": "desc"},
        timeout=30,
    )
    resp.raise_for_status()
    campaigns = resp.json().get("campaigns", [])
    for c in campaigns:
        if c.get("name") == campaign_name and c.get("status") in ALREADY_SENT_STATUSES:
            return c
    return None


def create_campaign(api_key: str, campaign_name: str, subject: str, html_content: str,
                     sender_email: str, sender_name: str, list_id: int) -> int:
    payload = {
        "name": campaign_name,
        "subject": subject,
        "sender": {"name": sender_name, "email": sender_email},
        "htmlContent": html_content,
        "recipients":
